language: python
python:
    - "2.6"
    - "2.7"
    - "3.3"
    - "3.4"
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq -y rpm
install:
    - if [[ "$(python --version 2>&1)" =~ Python\ (2\.*) ]]; then pip install -U jinja2; else echo "Skipping JINJA2 for $(python --version 2>&1)."; fi
    - pip install -rtest-requirements.txt
    - pip install -e ./
script:
    - if [[ "$(python --version 2>&1)" =~ Python\ (2\.7.*|3\.[3-4].*) ]]; then pep8 rpmvenv/; else echo "Skipping PEP8 for $(python --version 2>&1)."; fi
    - if [[ "$(python --version 2>&1)" =~ Python\ (2\.7.*|3\.[3-4].*) ]]; then pyflakes rpmvenv/; else echo "Skipping PyFlakes for $(python --version 2>&1)."; fi
    - py.test tests/
